### ISSUE TITLE
Emergency days not showing on the calendar for some users 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#376] opened 2024-03-24 10:27 UTC
it happened for 3 users (Ashraf, Eslam, Sameh) 
e.g. when adding an emergency for Ashraf on the 9th of Jan it appeared and got disappeared, but it has been deducted from his balance. 
e.g. Added same day as an emergency for Eslam, when refreshed it shows the 2 days on 24th of Jan and suddenly the 2nd day disappear 
e.g Sameh emergency on the 30th of Jan not showing  

<img width="1438" alt="Screenshot 2024-03-24 at 12 21 12 PM" src="https://github.com/codescalers/CSHR/assets/14869003/3a162058-fae9-41c0-b2d5-3e655341d515">
<img width="1428" alt="Screenshot 2024-03-24 at 12 22 14 PM" src="https://github.com/codescalers/CSHR/assets/14869003/15bd6c89-73ee-4196-81a1-3df03d1d1f43">

**Comment by maayarosama** [comment] 2024-03-25 11:47
Duplicate of #353

**Closed as completed by maayarosama** 2024-03-25 11:47 UTC
