### ISSUE TITLE
Set vacation balance for specific user

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#344] opened 2024-02-06 09:23 UTC
When trying to set vacation balance for a specific user, it only shows the people from page 1 of the Egypt office 
<img width="1436" alt="Screenshot 2024-02-06 at 11 21 55 AM" src="https://github.com/codescalers/CSHR/assets/14869003/f149a8c7-8f70-4954-9f8c-751427ca0780">

**Comment by zaelgohary** [comment] 2024-02-06 09:45
I tried to compare the users with the deployed QA version and both have the same result. Maybe the issue is from the API itself? what do you think? @Mahmoud-Emad 

![image](https://github.com/codescalers/CSHR/assets/40770501/b4cd1deb-6ec1-4e0a-ab93-964eb365475a)
![image](https://github.com/codescalers/CSHR/assets/40770501/1bd2a965-a3e6-4b0e-904c-3f01f12de8e1)

**Comment by Mahmoud-Emad** [comment] 2024-02-06 09:49
@zaelgohary,

As observed, the API response indicates that the count is greater than or equal to 20, implying that all users in the admin office have been retrieved. However, to access additional pages, it is necessary to make another request using the `next-page` URL.

![image](https://github.com/codescalers/CSHR/assets/57001890/f83c82a4-436e-42e4-904f-f4d4c65ad0e9)

I propose making a `load more` button to load more users and the request should be done by the returned URL

**Comment by Mahmoud-Emad** [comment] 2024-03-12 10:48
Closed as fixed, please if you notice that the issue still exists open it again.

**Closed as completed by Mahmoud-Emad** 2024-03-12 10:48 UTC
Labels: enhancement, Front End Feature
