### ISSUE TITLE
Admin access to remove a vacation

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#377] opened 2024-03-24 10:35 UTC
Can we give the admin an access to remove an already exciting vacation in case the user didn't actually use this vacation. 
so we can add a button for admin only, delete vacation and the reason to delete this vacation text window where the admin state why they want to delete the vacation 

<img width="1435" alt="Screenshot 2024-03-24 at 12 30 01 PM" src="https://github.com/codescalers/CSHR/assets/14869003/00542da5-308a-487e-b925-092e6b8f0491">

**Comment by maayarosama** [comment] 2024-03-25 11:42
duplicate of #247

**Closed as completed by maayarosama** 2024-03-25 11:42 UTC
